### ISSUE TITLE
Firebase not supported conversations

### ISSUE THREAD

**Issue by fl3xice** [grammyjs/grammY#510]
```
Error in middleware: 3 INVALID_ARGUMENT: Cannot convert an array value in an array value.
    Error: 3 INVALID_ARGUMENT: Cannot convert an array value in an array value.
        at callErrorFromStatus (D:\Projects\code-now-bot\node_modules\@grpc\grpc-js\src\call.ts:81:17)
        at Object.onReceiveStatus (D:\Projects\code-now-bot\node_modules\@grpc\grpc-js\src\client.ts:356:55)
        at Object.onReceiveStatus (D:\Projects\code-now-bot\node_modules\@grpc\grpc-js\src\client-interceptors.ts:454:34)
        at Object.onReceiveStatus (D:\Projects\code-now-bot\node_modules\@grpc\grpc-js\src\client-interceptors.ts:416:48)
        at D:\Projects\code-now-bot\node_modules\@grpc\grpc-js\src\resolving-call.ts:111:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

```ts
export async function checkoutOrder(
  conversation: MyConversation,
  ctx: CodeNowBotContext,
) {
  await ctx.reply(getTextByContext("questions.details.message", ctx));
  const orderDetails = await conversation.form.text();
  botLogger.debug(orderDetails);
  return;
}
```

I got this when try to use conversations with firebase storage adapter

**Comment by roj1512** [comment]
Are you using `@grammyjs/storage-firestore`?

**Comment by roj1512** [comment]
The stack trace doesn’t even include the word grammY...

**Comment by fl3xice** [comment]
> Are you using ?`@grammyjs/storage-firestore`

Yeah

**Comment by fl3xice** [comment]
> The stack trace doesn’t even include the word grammY...

I found the same problem in the archived repository, here is the [Issue](https://github.com/grammyjs/storages/issues/167)

**Comment by KnorpelSenf** [comment]
Is Firestore unable to handle nested arrays?
