### ISSUE TITLE
Trying to run simple example but it failed

### ISSUE THREAD

**Issue by ProgrammingLife** [grammyjs/grammY#64]
My bot.ts:
```
import { Bot } from "grammy";
const bot = new Bot( "token" );
bot.command( "start", ( ctx ) => ctx.reply( "Welcome! Up and running." ) );
bot.on( "message", ( ctx ) => ctx.reply( "Got another message!" ) );
bot.start();
```

Then:
```
» npx tsc

» node bot1.js
/home/user/nodejs/node_modules/grammy/out/core/client.js:110
            throw new error_js_1.GrammyError(`Call to '${method}' failed!`, data, method, payload);
                  ^

GrammyError: Call to 'getMe' failed! (404: Not Found)
    at ApiClient.callApi (/home/user/nodejs/node_modules/grammy/out/core/client.js:110:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bot.init (/home/user/nodejs/node_modules/grammy/out/bot.js:167:24)
    at async Bot.start (/home/user/nodejs/node_modules/grammy/out/bot.js:251:9) {
  method: 'getMe',
  payload: undefined,
  ok: false,
  error_code: 404,
  description: 'Not Found',
  parameters: {}
}

Node.js v17.0.1
```

I installed grammy via: `npm i grammy`.
What have I missed?

**Comment by EdJoPaTo** [comment]
`getMe` is the first thing done on startup. Seeing it failing indicates something with the telegram connection might be wrong.

Have you supply a correct bot token from [@BotFather](https://telegram.me/BotFather) like described in the [Getting Started Guide](https://grammy.dev/guide/getting-started.html#getting-started-on-node-js)?
