### ISSUE TITLE
Runner socket hang up on Heroku

### ISSUE THREAD

**Issue by rskvazh** [grammyjs/grammY#671]
I've got this errors every 30 seconds after some activity on heroku instance. Trying decrease the timeout in FetchOptions to 20 seconds - interval between errors becomes ~20 secs.

I've running with `run(bot, { runner: { fetch: { timeout: 20 } } })`

```
[grammY runner] Error while fetching updates:
Dec 04 06:43:47 app/bot.1 [grammY runner] HttpError: Network request for 'getUpdates' failed!
Dec 04 06:43:47 app/bot.1     at /app/node_modules/grammy/out/core/error.js:85:15
Dec 04 06:43:47 app/bot.1     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Dec 04 06:43:47 app/bot.1     at async ApiClient.call (/app/node_modules/grammy/out/core/client.js:54:29)
Dec 04 06:43:47 app/bot.1     at async ApiClient.callApi (/app/node_modules/grammy/out/core/client.js:93:22)
Dec 04 06:43:47 app/bot.1     at async Object.fetchUpdates [as supply] (/app/node_modules/@grammyjs/runner/out/runner.js:96:27)
Dec 04 06:43:47 app/bot.1     at async worker (/app/node_modules/@grammyjs/runner/out/source.js:63:31)
Dec 04 06:43:47 app/bot.1     at async runner (/app/node_modules/@grammyjs/runner/out/runner.js:142:30) {
Dec 04 06:43:47 app/bot.1   error: FetchError: request to https://api.telegram.org/bot***/getUpdates failed, reason: socket hang up
Dec 04 06:43:47 app/bot.1       at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1501:11)
Dec 04 06:43:47 app/bot.1       at ClientRequest.emit (node:events:518:28)
Dec 04 06:43:47 app/bot.1       at emitErrorEvent (node:_http_client:103:11)
Dec 04 06:43:47 app/bot.1       at TLSSocket.socketOnEnd (node:_http_client:530:5)
Dec 04 06:43:47 app/bot.1       at TLSSocket.emit (node:events:530:35)
Dec 04 06:43:47 app/bot.1       at endReadableNT (node:internal/streams/readable:1698:12)
Dec 04 06:43:47 app/bot.1       at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
Dec 04 06:43:47 app/bot.1     type: 'system',
Dec 04 06:43:47 app/bot.1     errno: 'ECONNRESET',
Dec 04 06:43:47 app/bot.1     code: 'ECONNRESET'
Dec 04 06:43:47 app/bot.1   }
Dec 04 06:43:47 app/bot.1 }
```

**Comment by KnorpelSenf** [comment]
This is expected. All networks are unreliable to some extent, and all requests can fail. When they do, grammY runner logs this error and retries the request automatically. Everything is working as expected.

**Comment by rskvazh** [comment]
I think this error often occurs because Telegram’s side closes the connection when the timeout parameter is reached, and sometimes this happens earlier than the client code’s timeout. Maybe try adding 1 second to the Telegram fetch options?
